[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "probe-rs run --chip RP2040"
#runner = "elf2uf2 -d"
runner = "sudo picotool load -t elf "

[build]
target = "thumbv6m-none-eabi"
